import Head from 'next/head'
import Companies from '../components/companies/Companies'
import Features from '../components/features/Features'
import Header from '../components/header/Header'
import Hero from '../components/hero/Hero'
import Footer from '../components/footer/Footer'


export default function Home() {
  return (
    <div>
      <Head>
        <title>App Lab</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Header />
      <Hero />
      <Companies />
      <Features />
      <Footer />
    </div>
  )
}


